name: CI Nuxt app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files to public folder
        run: |
          cp -fR ./* /var/www/630.kz
          echo 'Copying is done'
          cd /var/www/630.kz

  build:
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Install deps
        run: npm install
      - name: Build app
        run: npm run build