name: 'CI Nuxt app'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files to public folder
        run: |
          npm run build
          cp -fR ./* /var/www/630.kz
          echo 'Copying is done'
          cd /var/www/630.kz