name: "CI Nuxt app"

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm install
      - name: Build the app
        run: npm run build
  
